name: Publish

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v1
    - name: update gatsby
      run: npm update gatsby
    - name: firebase plugin install
      run: npm install firebase gatsby-plugin-firebase
    - uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.ACCESS_TOKEN}}
